image: datadog/dd-trace-java-docker-build:latest

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - GRADLE_OPTS="-Dorg.gradle.jvmargs='-Xmx1G -Xms64M' -Ddatadog.forkedMaxHeapSize=1G -Ddatadog.forkedMinHeapSize=64M" ./gradlew clean assemble --build-cache --parallel --stacktrace --no-daemon --max-workers=8
  artifacts:
    paths:
      - "**/build/libs/*.jar"
test:
  stage: test
  script:
    - GRADLE_OPTS="-Ddatadog.forkedMaxHeapSize=4G -Ddatadog.forkedMinHeapSize=64M" ./gradlew test --build-cache --parallel --stacktrace --no-daemon --max-workers=6
  artifacts:
    reports:
      junit: "**/build/test-results/*/TEST-*.xml"
