version: "3"
# remember to use this compose file __ONLY__ for development/testing purposes

services:
  testagent:
    image: williamconti549/dd-apm-test-agent:pool-failures
    ports:
      - "127.0.0.1:8126:8126"
    environment:
      - LOG_LEVEL=DEBUG
      - SNAPSHOT_CI
      - DD_SUPPRESS_TRACE_PARSE_ERRORS=true
      - DD_POOL_TRACE_CHECK_FAILURES=true

